name: material_dialog_example
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^8.0.0-dev.1
  ngcomponents:
    path: ../../ngcomponents
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^1.0.0

